mysql:
  image: mysql:5.7
  ports:
    - '3306:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=devchallenge_11_2

app:
  build: .
  links:
    - mysql
  ports:
    - "8000:8000"