mysql:
  image: mysql:5.7
  ports:
    - '3306:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=devchallenge_11_2
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_PORT_3306_TCP_PORT=3306
    - PORT=3306

app:
  build: .
  links:
    - mysql
  ports:
    - "8000:8000"